In [1]:
import argparse
import os, sys
from utils.data_utils import *
from glob import glob
import pandas as pd
import numpy as np
import shutil
from tqdm import tqdm
%matplotlib inline  
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = [12,9]
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.colheader_justify', 'left')

In [2]:
def get_data_dir(a, t):
    if t:
        if a:
            data_dir = 'train_ex'
        else:
            data_dir = 'train'
    else:
        if a:
            data_dir = 'valid_ex'
        else:
            data_dir = 'valid'
    return data_dir

def load_loss_df(l_dirs, augmented=False, train=False):
    data_dir = get_data_dir(augmented, train)
    dataframes = []
    for d in l_dirs:
        dataframes.append(pd.read_csv(os.path.join('predictions', data_dir, d, 'models.csv')))

    df_l = pd.concat(dataframes, ignore_index=True)
    return df_l

def get_gt_name(a, t):
    if t:
        if a:
            name = 'Y_train_augmented.npz'
        else:
            name = 'Y_train.npz'
    else:
        if a:
            name = 'Y_valid_augmented.npz'
        else:
            name = 'Y_valid.npz'
    return name

def load_ground_truth(data_dir, augmented=False, train=False):
    gt_name = get_gt_name(augmented, train)
    y_true_path = os.path.join('augmented', data_dir, gt_name)
    y_true = npz_to_ndarray(np.load(y_true_path))
    return y_true

def load_preds(df_loss):
    preds = []
    for npz_path in tqdm(df_loss.res_path):
        p = npz_to_ndarray(np.load(npz_path))
        preds.append(p)
    return np.array(preds)

def load_test_df(l_dirs):
    dataframes = []
    for d in l_dirs:
        dataframes.append(pd.read_csv(os.path.join('test_predictions', d, 'models.csv')))

    df_l = pd.concat(dataframes, ignore_index=True)
    return df_l

def get_labels():
    labels = [
        'slash_burn',
        'clear',
        'blooming',
        'primary',
        'cloudy',
        'conventional_mine',
        'water',
        'haze',
        'cultivation',
        'partly_cloudy',
        'artisinal_mine',
        'habitation',
        'bare_ground',
        'blow_down',
        'agriculture',
        'road',
        'selective_logging'
    ]

    l_map = {l: i for i, l in enumerate(labels)}
    inv_map = {i: l for l, i in l_map.items()}
    return labels, l_map, inv_map

labels, label_map, inv_label_map = get_labels()

def to_tagging(one_hot_data, inv_label_map):
    res = pd.DataFrame(index=range(len(one_hot_data)), columns=['tags'])
    for j in tqdm(range(len(one_hot_data))):
        tags = []
        for i in range(17):
            if one_hot_data[j][i] == 1:
                tags.append(inv_label_map[i])
        res['tags'][j] = ' '.join(sorted(tags))
    return res

def get_test_df():
    inputs_dir = 'inputs'
    df_submission = pd.read_csv(os.path.join(inputs_dir, 'sample_submission_v2.csv'))
    return df_submission

def create_submission(pred, sufix):
    print("Reading submission dataframe")
    df_submission = get_test_df()
    print("Creating tags")
    p_tags = to_tagging(pred, inv_label_map)
    df_submission.tags = p_tags.tags
    submission_dir = os.path.join('submissions', 'ensemble_avg_test')
    if not os.path.exists(submission_dir):
        os.makedirs(submission_dir)
        
    file_name = 'submission_' + sufix + '.csv'
    print("Saving submission to file")
    df_submission.to_csv(os.path.join(submission_dir, file_name), index=False)
    print("%s created" % os.path.join(submission_dir, file_name))
    
def val_idx_to_test(val_idx, df_test, df_valid):
    res = [df_test[df_test.path == p].index[0] for p in df_valid.loc[val_idx].path]
    if len(res) != len(val_idx):
        missing_idx = -1
        for i in val_idx:
            if not df_valid.loc[i].path in list(df_test.path):
                missing_idx = i
        raise RuntimeError("Model %d not in the test dataframe" % missing_idx)
        
    return res

In [23]:
l_dirs = ['0.09']
df_valid = load_loss_df(l_dirs, augmented=True, train=False)
print("val dataframe size %d" % len(df_valid))
preds_valid = load_preds(df_valid)
print("val predictions shape %s" % str(preds_valid.shape))

  0%|          | 2/499 [00:00<00:28, 17.61it/s]

val dataframe size 499


100%|██████████| 499/499 [00:20<00:00, 24.34it/s]


val predictions shape (499, 64768, 17)


In [34]:
df_test = load_test_df(l_dirs)
print("test dataframe size %d" % len(df_test))
preds_test = load_preds(df_test)
print("val predictions shape %s" % str(preds_test.shape))

  6%|▌         | 3/50 [00:00<00:02, 22.57it/s]

test dataframe size 50


100%|██████████| 50/50 [00:01<00:00, 36.93it/s]

val predictions shape (50, 61191, 17)


In [6]:
y_true_valid = load_ground_truth('train_augmented_size_128_mult_8_seed_0', augmented=True, train=False)
print("Y ground truth shape %s" % str(y_true_valid.shape))

Y ground truth shape (64768, 17)


In [7]:
def vote(preds):
    return (preds.mean(axis=0) > 0.5).astype(int)

epsilon = 0.00001
def find_best_candidate(y_true, all_preds, ensemble):
    best_avg_score = 0
    best_candidate = None
    ensemble_preds = [all_preds[j] for j in ensemble]
    for i in tqdm(range(len(all_preds))):
        preds = ensemble_preds + [all_preds[i]]
        avg_pred = (np.mean(preds, axis=0) > 0.2).astype(int)
        avg_score = fbeta_score(y_true, avg_pred, beta=2, average='samples')
        if avg_score > best_avg_score:
            best_avg_score = avg_score                
            best_candidate = i          
                
    return best_candidate, best_avg_score

def optimize_score(y_true, preds, init_ensemble = [], exclude = []):
    best_ensemble = init_ensemble[:]
    best_score = 0
    scores = []
    counter = 0
    while True:
        best_candidate, ens_score = find_best_candidate(y_true, preds, ensemble=best_ensemble)
        sys.stdout.flush()
            
        if ens_score > (best_score + epsilon):
            best_ensemble.append(best_candidate)
            print("%d: Best candidate model is %d with improvement of %.5f" % (counter, best_candidate, ens_score-best_score))
            print("%d: Best ensemble %s" % (counter, best_ensemble))
            print("%d: New ensemble score %.5f" % (counter, ens_score))
            scores.append(ens_score)
            best_score = ens_score
            counter+=1
        else:
            print("Can't optimize any more")
            break
    
    return best_ensemble, scores

In [10]:
def optimize_with_split(n_splits, preds_in, y_true):
    preds = preds_in.copy()

    counter = 0
    bag_size = len(preds)/n_splits
    last_bag_size = len(preds) - bag_size*(n_splits-1)
    print("Split to bas of %d where last %d" % (bag_size, last_bag_size))

    all_ensembles = []
    all_scores = []
    orig_idxes = np.arange(len(preds))
    curr_idxes = orig_idxes.copy()
    while len(curr_idxes) > 0:
        print("Optimizing bag %d" % counter)
        selection = np.random.choice(curr_idxes, replace=False, \
                                     size=(bag_size if len(curr_idxes) > last_bag_size else last_bag_size))

        p = preds[selection]
        ensemble, scores = optimize_score(y_true, p)
        all_ensembles.append(selection[ensemble])
        all_scores.append(scores)
        curr_idxes = curr_idxes[[i not in selection for i in curr_idxes]]
        counter+=1

    best_scores = [slist[-1] for slist in all_scores]
    print(best_scores)
    print("Average score %.5f" % np.mean(best_scores))
    
    return all_ensembles, all_scores

In [18]:
# l = np.random.choice(np.arange(len(preds_valid)), size=32)
# preds_ = preds_valid[l].copy()
all_ensembles = []
all_scores = []
for i in range(3):
    print("\nIteration %d" % i)
    ensembles, scores = optimize_with_split(n_splits=3, preds_in=preds_valid, y_true=y_true_valid)
    all_ensembles += ensembles
    all_scores += scores


Iteration 0
Split to bas of 166 where last 166
Optimizing bag 0


  1%|          | 2/166 [00:00<00:11, 14.05it/s]

0: Best candidate model is 69 with improvement of 0.92802
0: Best ensemble [69]
0: New ensemble score 0.92802


  1%|          | 2/166 [00:00<00:12, 13.04it/s]

1: Best candidate model is 133 with improvement of 0.00189
1: Best ensemble [69, 133]
1: New ensemble score 0.92991


  1%|          | 2/166 [00:00<00:12, 13.28it/s]

2: Best candidate model is 124 with improvement of 0.00138
2: Best ensemble [69, 133, 124]
2: New ensemble score 0.93129


  1%|          | 1/166 [00:00<00:23,  7.05it/s]

3: Best candidate model is 101 with improvement of 0.00057
3: Best ensemble [69, 133, 124, 101]
3: New ensemble score 0.93186


  1%|          | 2/166 [00:00<00:12, 13.00it/s]

4: Best candidate model is 109 with improvement of 0.00027
4: Best ensemble [69, 133, 124, 101, 109]
4: New ensemble score 0.93213


  1%|          | 2/166 [00:00<00:12, 12.76it/s]

5: Best candidate model is 15 with improvement of 0.00030
5: Best ensemble [69, 133, 124, 101, 109, 15]
5: New ensemble score 0.93243


  1%|          | 1/166 [00:00<00:26,  6.32it/s]

6: Best candidate model is 159 with improvement of 0.00032
6: Best ensemble [69, 133, 124, 101, 109, 15, 159]
6: New ensemble score 0.93275


  1%|          | 2/166 [00:00<00:13, 11.98it/s]

7: Best candidate model is 10 with improvement of 0.00008
7: Best ensemble [69, 133, 124, 101, 109, 15, 159, 10]
7: New ensemble score 0.93282


100%|██████████| 166/166 [00:13<00:00, 11.85it/s]


Can't optimize any more
Optimizing bag 1


  1%|          | 1/166 [00:00<00:23,  7.13it/s]

0: Best candidate model is 115 with improvement of 0.92763
0: Best ensemble [115]
0: New ensemble score 0.92763


  1%|          | 1/166 [00:00<00:23,  7.05it/s]

1: Best candidate model is 116 with improvement of 0.00284
1: Best ensemble [115, 116]
1: New ensemble score 0.93047


  1%|          | 2/166 [00:00<00:12, 12.99it/s]

2: Best candidate model is 64 with improvement of 0.00093
2: Best ensemble [115, 116, 64]
2: New ensemble score 0.93139


  1%|          | 2/166 [00:00<00:12, 13.45it/s]

3: Best candidate model is 15 with improvement of 0.00066
3: Best ensemble [115, 116, 64, 15]
3: New ensemble score 0.93206


  1%|          | 1/166 [00:00<00:26,  6.24it/s]

4: Best candidate model is 23 with improvement of 0.00014
4: Best ensemble [115, 116, 64, 15, 23]
4: New ensemble score 0.93219


  1%|          | 2/166 [00:00<00:12, 12.78it/s]

5: Best candidate model is 165 with improvement of 0.00028
5: Best ensemble [115, 116, 64, 15, 23, 165]
5: New ensemble score 0.93247


  1%|          | 1/166 [00:00<00:24,  6.82it/s]

6: Best candidate model is 153 with improvement of 0.00019
6: Best ensemble [115, 116, 64, 15, 23, 165, 153]
6: New ensemble score 0.93266


  1%|          | 2/166 [00:00<00:13, 12.50it/s]

7: Best candidate model is 5 with improvement of 0.00007
7: Best ensemble [115, 116, 64, 15, 23, 165, 153, 5]
7: New ensemble score 0.93273


  1%|          | 2/166 [00:00<00:13, 11.89it/s]

8: Best candidate model is 128 with improvement of 0.00015
8: Best ensemble [115, 116, 64, 15, 23, 165, 153, 5, 128]
8: New ensemble score 0.93289


  1%|          | 1/166 [00:00<00:27,  6.10it/s]

9: Best candidate model is 115 with improvement of 0.00008
9: Best ensemble [115, 116, 64, 15, 23, 165, 153, 5, 128, 115]
9: New ensemble score 0.93296


  1%|          | 2/166 [00:00<00:13, 11.92it/s]

10: Best candidate model is 97 with improvement of 0.00009
10: Best ensemble [115, 116, 64, 15, 23, 165, 153, 5, 128, 115, 97]
10: New ensemble score 0.93305


  1%|          | 2/166 [00:00<00:13, 11.80it/s]

11: Best candidate model is 46 with improvement of 0.00005
11: Best ensemble [115, 116, 64, 15, 23, 165, 153, 5, 128, 115, 97, 46]
11: New ensemble score 0.93310


  1%|          | 1/166 [00:00<00:17,  9.68it/s]

12: Best candidate model is 159 with improvement of 0.00009
12: Best ensemble [115, 116, 64, 15, 23, 165, 153, 5, 128, 115, 97, 46, 159]
12: New ensemble score 0.93319


100%|██████████| 166/166 [00:16<00:00, 10.30it/s]


Can't optimize any more
Optimizing bag 2


  1%|          | 2/166 [00:00<00:12, 13.54it/s]

0: Best candidate model is 89 with improvement of 0.92613
0: Best ensemble [89]
0: New ensemble score 0.92613


  1%|          | 1/166 [00:00<00:26,  6.34it/s]

1: Best candidate model is 26 with improvement of 0.00365
1: Best ensemble [89, 26]
1: New ensemble score 0.92978


  1%|          | 2/166 [00:00<00:12, 13.38it/s]

2: Best candidate model is 24 with improvement of 0.00167
2: Best ensemble [89, 26, 24]
2: New ensemble score 0.93145


  1%|          | 2/166 [00:00<00:12, 13.19it/s]

3: Best candidate model is 48 with improvement of 0.00066
3: Best ensemble [89, 26, 24, 48]
3: New ensemble score 0.93210


  1%|          | 2/166 [00:00<00:12, 13.03it/s]

4: Best candidate model is 98 with improvement of 0.00021
4: Best ensemble [89, 26, 24, 48, 98]
4: New ensemble score 0.93231


  1%|          | 2/166 [00:00<00:12, 12.86it/s]

5: Best candidate model is 115 with improvement of 0.00029
5: Best ensemble [89, 26, 24, 48, 98, 115]
5: New ensemble score 0.93260


  1%|          | 2/166 [00:00<00:14, 11.18it/s]

6: Best candidate model is 37 with improvement of 0.00032
6: Best ensemble [89, 26, 24, 48, 98, 115, 37]
6: New ensemble score 0.93292


100%|██████████| 166/166 [00:13<00:00, 12.22it/s]


Can't optimize any more
[0.93282496466409714, 0.93318993130235728, 0.93291977901832968]
Average score 0.93298

Iteration 1
Split to bas of 166 where last 166
Optimizing bag 0


  1%|          | 2/166 [00:00<00:11, 13.74it/s]

0: Best candidate model is 123 with improvement of 0.92802
0: Best ensemble [123]
0: New ensemble score 0.92802


  1%|          | 2/166 [00:00<00:12, 13.54it/s]

1: Best candidate model is 78 with improvement of 0.00215
1: Best ensemble [123, 78]
1: New ensemble score 0.93017


  1%|          | 2/166 [00:00<00:12, 13.06it/s]

2: Best candidate model is 71 with improvement of 0.00112
2: Best ensemble [123, 78, 71]
2: New ensemble score 0.93129


  1%|          | 1/166 [00:00<00:24,  6.80it/s]

3: Best candidate model is 74 with improvement of 0.00056
3: Best ensemble [123, 78, 71, 74]
3: New ensemble score 0.93186


  1%|          | 1/166 [00:00<00:24,  6.81it/s]

4: Best candidate model is 24 with improvement of 0.00055
4: Best ensemble [123, 78, 71, 74, 24]
4: New ensemble score 0.93240


  1%|          | 2/166 [00:00<00:13, 12.21it/s]

5: Best candidate model is 33 with improvement of 0.00032
5: Best ensemble [123, 78, 71, 74, 24, 33]
5: New ensemble score 0.93272


  1%|          | 1/166 [00:00<00:24,  6.63it/s]

6: Best candidate model is 149 with improvement of 0.00009
6: Best ensemble [123, 78, 71, 74, 24, 33, 149]
6: New ensemble score 0.93282


  1%|          | 1/166 [00:00<00:22,  7.31it/s]

7: Best candidate model is 142 with improvement of 0.00010
7: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142]
7: New ensemble score 0.93291


  1%|          | 1/166 [00:00<00:25,  6.58it/s]

8: Best candidate model is 116 with improvement of 0.00012
8: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142, 116]
8: New ensemble score 0.93304


  1%|          | 2/166 [00:00<00:13, 11.77it/s]

9: Best candidate model is 90 with improvement of 0.00006
9: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142, 116, 90]
9: New ensemble score 0.93309


  1%|          | 2/166 [00:00<00:13, 11.96it/s]

10: Best candidate model is 98 with improvement of 0.00008
10: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142, 116, 90, 98]
10: New ensemble score 0.93318


  1%|          | 2/166 [00:00<00:13, 11.72it/s]

11: Best candidate model is 71 with improvement of 0.00012
11: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142, 116, 90, 98, 71]
11: New ensemble score 0.93330


  1%|          | 1/166 [00:00<00:17,  9.60it/s]

12: Best candidate model is 140 with improvement of 0.00001
12: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142, 116, 90, 98, 71, 140]
12: New ensemble score 0.93331


  1%|          | 1/166 [00:00<00:17,  9.59it/s]

13: Best candidate model is 54 with improvement of 0.00002
13: Best ensemble [123, 78, 71, 74, 24, 33, 149, 142, 116, 90, 98, 71, 140, 54]
13: New ensemble score 0.93333


100%|██████████| 166/166 [00:17<00:00,  9.80it/s]


Can't optimize any more
Optimizing bag 1


  1%|          | 1/166 [00:00<00:23,  7.04it/s]

0: Best candidate model is 13 with improvement of 0.92763
0: Best ensemble [13]
0: New ensemble score 0.92763


  1%|          | 2/166 [00:00<00:12, 13.03it/s]

1: Best candidate model is 111 with improvement of 0.00251
1: Best ensemble [13, 111]
1: New ensemble score 0.93014


  1%|          | 1/166 [00:00<00:23,  6.93it/s]

2: Best candidate model is 142 with improvement of 0.00105
2: Best ensemble [13, 111, 142]
2: New ensemble score 0.93119


  1%|          | 1/166 [00:00<00:24,  6.62it/s]

3: Best candidate model is 122 with improvement of 0.00051
3: Best ensemble [13, 111, 142, 122]
3: New ensemble score 0.93170


  1%|          | 1/166 [00:00<00:24,  6.83it/s]

4: Best candidate model is 13 with improvement of 0.00020
4: Best ensemble [13, 111, 142, 122, 13]
4: New ensemble score 0.93190


  1%|          | 1/166 [00:00<00:21,  7.82it/s]

5: Best candidate model is 103 with improvement of 0.00032
5: Best ensemble [13, 111, 142, 122, 13, 103]
5: New ensemble score 0.93222


  1%|          | 1/166 [00:00<00:23,  6.94it/s]

6: Best candidate model is 22 with improvement of 0.00027
6: Best ensemble [13, 111, 142, 122, 13, 103, 22]
6: New ensemble score 0.93249


  1%|          | 2/166 [00:00<00:14, 11.71it/s]

7: Best candidate model is 93 with improvement of 0.00014
7: Best ensemble [13, 111, 142, 122, 13, 103, 22, 93]
7: New ensemble score 0.93263


  1%|          | 2/166 [00:00<00:14, 11.58it/s]

8: Best candidate model is 108 with improvement of 0.00001
8: Best ensemble [13, 111, 142, 122, 13, 103, 22, 93, 108]
8: New ensemble score 0.93264


  1%|          | 1/166 [00:00<00:25,  6.44it/s]

9: Best candidate model is 4 with improvement of 0.00008
9: Best ensemble [13, 111, 142, 122, 13, 103, 22, 93, 108, 4]
9: New ensemble score 0.93272


100%|██████████| 166/166 [00:14<00:00, 11.26it/s]


Can't optimize any more
Optimizing bag 2


  1%|          | 2/166 [00:00<00:11, 13.83it/s]

0: Best candidate model is 8 with improvement of 0.92691
0: Best ensemble [8]
0: New ensemble score 0.92691


  1%|          | 1/166 [00:00<00:23,  6.91it/s]

1: Best candidate model is 0 with improvement of 0.00355
1: Best ensemble [8, 0]
1: New ensemble score 0.93046


  1%|          | 2/166 [00:00<00:12, 13.43it/s]

2: Best candidate model is 113 with improvement of 0.00098
2: Best ensemble [8, 0, 113]
2: New ensemble score 0.93143


  1%|          | 2/166 [00:00<00:12, 13.27it/s]

3: Best candidate model is 40 with improvement of 0.00037
3: Best ensemble [8, 0, 113, 40]
3: New ensemble score 0.93180


  1%|          | 2/166 [00:00<00:12, 13.00it/s]

4: Best candidate model is 80 with improvement of 0.00043
4: Best ensemble [8, 0, 113, 40, 80]
4: New ensemble score 0.93223


  1%|          | 2/166 [00:00<00:12, 12.80it/s]

5: Best candidate model is 123 with improvement of 0.00023
5: Best ensemble [8, 0, 113, 40, 80, 123]
5: New ensemble score 0.93245


  1%|          | 2/166 [00:00<00:13, 12.02it/s]

6: Best candidate model is 14 with improvement of 0.00011
6: Best ensemble [8, 0, 113, 40, 80, 123, 14]
6: New ensemble score 0.93256


  1%|          | 2/166 [00:00<00:13, 12.42it/s]

7: Best candidate model is 82 with improvement of 0.00010
7: Best ensemble [8, 0, 113, 40, 80, 123, 14, 82]
7: New ensemble score 0.93266


  1%|          | 2/166 [00:00<00:13, 12.21it/s]

8: Best candidate model is 124 with improvement of 0.00011
8: Best ensemble [8, 0, 113, 40, 80, 123, 14, 82, 124]
8: New ensemble score 0.93277


  1%|          | 2/166 [00:00<00:13, 11.90it/s]

9: Best candidate model is 140 with improvement of 0.00012
9: Best ensemble [8, 0, 113, 40, 80, 123, 14, 82, 124, 140]
9: New ensemble score 0.93289


  1%|          | 2/166 [00:00<00:13, 11.86it/s]

10: Best candidate model is 33 with improvement of 0.00010
10: Best ensemble [8, 0, 113, 40, 80, 123, 14, 82, 124, 140, 33]
10: New ensemble score 0.93299


  1%|          | 2/166 [00:00<00:14, 11.68it/s]

11: Best candidate model is 131 with improvement of 0.00003
11: Best ensemble [8, 0, 113, 40, 80, 123, 14, 82, 124, 140, 33, 131]
11: New ensemble score 0.93302


  1%|          | 1/166 [00:00<00:20,  8.23it/s]

12: Best candidate model is 160 with improvement of 0.00008
12: Best ensemble [8, 0, 113, 40, 80, 123, 14, 82, 124, 140, 33, 131, 160]
12: New ensemble score 0.93310


100%|██████████| 166/166 [00:17<00:00,  9.81it/s]


Can't optimize any more
[0.93333410006506912, 0.93271591575250434, 0.93309748711133944]
Average score 0.93305

Iteration 2
Split to bas of 166 where last 166
Optimizing bag 0


  1%|          | 2/166 [00:00<00:12, 12.97it/s]

0: Best candidate model is 126 with improvement of 0.92613
0: Best ensemble [126]
0: New ensemble score 0.92613


  1%|          | 1/166 [00:00<00:19,  8.65it/s]

1: Best candidate model is 22 with improvement of 0.00354
1: Best ensemble [126, 22]
1: New ensemble score 0.92967


  1%|          | 2/166 [00:00<00:12, 13.45it/s]

2: Best candidate model is 73 with improvement of 0.00134
2: Best ensemble [126, 22, 73]
2: New ensemble score 0.93101


  1%|          | 1/166 [00:00<00:24,  6.79it/s]

3: Best candidate model is 119 with improvement of 0.00096
3: Best ensemble [126, 22, 73, 119]
3: New ensemble score 0.93198


  1%|          | 2/166 [00:00<00:12, 12.68it/s]

4: Best candidate model is 160 with improvement of 0.00026
4: Best ensemble [126, 22, 73, 119, 160]
4: New ensemble score 0.93224


  1%|          | 2/166 [00:00<00:13, 12.15it/s]

5: Best candidate model is 96 with improvement of 0.00032
5: Best ensemble [126, 22, 73, 119, 160, 96]
5: New ensemble score 0.93256


  1%|          | 2/166 [00:00<00:12, 12.77it/s]

6: Best candidate model is 136 with improvement of 0.00014
6: Best ensemble [126, 22, 73, 119, 160, 96, 136]
6: New ensemble score 0.93271


  1%|          | 1/166 [00:00<00:28,  5.89it/s]

7: Best candidate model is 78 with improvement of 0.00003
7: Best ensemble [126, 22, 73, 119, 160, 96, 136, 78]
7: New ensemble score 0.93274


  1%|          | 2/166 [00:00<00:13, 11.84it/s]

8: Best candidate model is 49 with improvement of 0.00011
8: Best ensemble [126, 22, 73, 119, 160, 96, 136, 78, 49]
8: New ensemble score 0.93285


  1%|          | 2/166 [00:00<00:13, 11.96it/s]

9: Best candidate model is 94 with improvement of 0.00006
9: Best ensemble [126, 22, 73, 119, 160, 96, 136, 78, 49, 94]
9: New ensemble score 0.93291


  1%|          | 2/166 [00:00<00:14, 11.29it/s]

10: Best candidate model is 96 with improvement of 0.00001
10: Best ensemble [126, 22, 73, 119, 160, 96, 136, 78, 49, 94, 96]
10: New ensemble score 0.93292


100%|██████████| 166/166 [00:15<00:00, 10.60it/s]


Can't optimize any more
Optimizing bag 1


  1%|          | 2/166 [00:00<00:12, 13.00it/s]

0: Best candidate model is 150 with improvement of 0.92802
0: Best ensemble [150]
0: New ensemble score 0.92802


  1%|          | 2/166 [00:00<00:12, 13.52it/s]

1: Best candidate model is 123 with improvement of 0.00243
1: Best ensemble [150, 123]
1: New ensemble score 0.93045


  1%|          | 1/166 [00:00<00:19,  8.26it/s]

2: Best candidate model is 25 with improvement of 0.00107
2: Best ensemble [150, 123, 25]
2: New ensemble score 0.93152


  1%|          | 2/166 [00:00<00:13, 12.20it/s]

3: Best candidate model is 38 with improvement of 0.00082
3: Best ensemble [150, 123, 25, 38]
3: New ensemble score 0.93235


  1%|          | 2/166 [00:00<00:14, 11.54it/s]

4: Best candidate model is 44 with improvement of 0.00040
4: Best ensemble [150, 123, 25, 38, 44]
4: New ensemble score 0.93275


  1%|          | 1/166 [00:00<00:24,  6.75it/s]

5: Best candidate model is 26 with improvement of 0.00013
5: Best ensemble [150, 123, 25, 38, 44, 26]
5: New ensemble score 0.93288


  1%|          | 2/166 [00:00<00:13, 12.45it/s]

6: Best candidate model is 132 with improvement of 0.00018
6: Best ensemble [150, 123, 25, 38, 44, 26, 132]
6: New ensemble score 0.93306


  1%|          | 2/166 [00:00<00:13, 12.04it/s]

7: Best candidate model is 35 with improvement of 0.00006
7: Best ensemble [150, 123, 25, 38, 44, 26, 132, 35]
7: New ensemble score 0.93313


  1%|          | 2/166 [00:00<00:13, 11.79it/s]

8: Best candidate model is 25 with improvement of 0.00014
8: Best ensemble [150, 123, 25, 38, 44, 26, 132, 35, 25]
8: New ensemble score 0.93326


  1%|          | 2/166 [00:00<00:13, 12.11it/s]

9: Best candidate model is 39 with improvement of 0.00002
9: Best ensemble [150, 123, 25, 38, 44, 26, 132, 35, 25, 39]
9: New ensemble score 0.93328


100%|██████████| 166/166 [00:15<00:00, 10.09it/s]


Can't optimize any more
Optimizing bag 2


  1%|          | 2/166 [00:00<00:11, 13.83it/s]

0: Best candidate model is 42 with improvement of 0.92691
0: Best ensemble [42]
0: New ensemble score 0.92691


  1%|          | 2/166 [00:00<00:12, 13.65it/s]

1: Best candidate model is 146 with improvement of 0.00292
1: Best ensemble [42, 146]
1: New ensemble score 0.92983


  1%|          | 2/166 [00:00<00:12, 13.39it/s]

2: Best candidate model is 109 with improvement of 0.00124
2: Best ensemble [42, 146, 109]
2: New ensemble score 0.93106


  1%|          | 2/166 [00:00<00:12, 13.17it/s]

3: Best candidate model is 20 with improvement of 0.00051
3: Best ensemble [42, 146, 109, 20]
3: New ensemble score 0.93158


  1%|          | 2/166 [00:00<00:12, 13.07it/s]

4: Best candidate model is 95 with improvement of 0.00028
4: Best ensemble [42, 146, 109, 20, 95]
4: New ensemble score 0.93185


  1%|          | 2/166 [00:00<00:12, 13.04it/s]

5: Best candidate model is 153 with improvement of 0.00022
5: Best ensemble [42, 146, 109, 20, 95, 153]
5: New ensemble score 0.93207


  1%|          | 1/166 [00:00<00:24,  6.68it/s]

6: Best candidate model is 4 with improvement of 0.00007
6: Best ensemble [42, 146, 109, 20, 95, 153, 4]
6: New ensemble score 0.93214


  1%|          | 1/166 [00:00<00:17,  9.53it/s]

7: Best candidate model is 56 with improvement of 0.00017
7: Best ensemble [42, 146, 109, 20, 95, 153, 4, 56]
7: New ensemble score 0.93231


100%|██████████| 166/166 [00:13<00:00, 11.96it/s]


Can't optimize any more
[0.9329213686182346, 0.93328039099387672, 0.93231324468846577]
Average score 0.93284

Iteration 3
Split to bas of 166 where last 166
Optimizing bag 0


  1%|          | 1/166 [00:00<00:23,  6.97it/s]

0: Best candidate model is 51 with improvement of 0.92802
0: Best ensemble [51]
0: New ensemble score 0.92802


  1%|          | 2/166 [00:00<00:12, 13.38it/s]

1: Best candidate model is 21 with improvement of 0.00189
1: Best ensemble [51, 21]
1: New ensemble score 0.92991


  1%|          | 2/166 [00:00<00:12, 13.41it/s]

2: Best candidate model is 144 with improvement of 0.00138
2: Best ensemble [51, 21, 144]
2: New ensemble score 0.93129


  1%|          | 2/166 [00:00<00:12, 13.23it/s]

3: Best candidate model is 54 with improvement of 0.00057
3: Best ensemble [51, 21, 144, 54]
3: New ensemble score 0.93186


  1%|          | 1/166 [00:00<00:24,  6.63it/s]

4: Best candidate model is 36 with improvement of 0.00005
4: Best ensemble [51, 21, 144, 54, 36]
4: New ensemble score 0.93191


  1%|          | 1/166 [00:00<00:25,  6.57it/s]

5: Best candidate model is 47 with improvement of 0.00024
5: Best ensemble [51, 21, 144, 54, 36, 47]
5: New ensemble score 0.93215


  1%|          | 2/166 [00:00<00:13, 11.84it/s]

6: Best candidate model is 123 with improvement of 0.00006
6: Best ensemble [51, 21, 144, 54, 36, 47, 123]
6: New ensemble score 0.93221


  1%|          | 2/166 [00:00<00:13, 12.35it/s]

7: Best candidate model is 15 with improvement of 0.00013
7: Best ensemble [51, 21, 144, 54, 36, 47, 123, 15]
7: New ensemble score 0.93234


100%|██████████| 166/166 [00:13<00:00, 12.41it/s]


Can't optimize any more
Optimizing bag 1


  1%|          | 2/166 [00:00<00:11, 13.86it/s]

0: Best candidate model is 53 with improvement of 0.92666
0: Best ensemble [53]
0: New ensemble score 0.92666


  1%|          | 1/166 [00:00<00:23,  6.98it/s]

1: Best candidate model is 37 with improvement of 0.00363
1: Best ensemble [53, 37]
1: New ensemble score 0.93029


  1%|          | 1/166 [00:00<00:24,  6.85it/s]

2: Best candidate model is 117 with improvement of 0.00107
2: Best ensemble [53, 37, 117]
2: New ensemble score 0.93135


  1%|          | 2/166 [00:00<00:12, 13.25it/s]

3: Best candidate model is 9 with improvement of 0.00038
3: Best ensemble [53, 37, 117, 9]
3: New ensemble score 0.93173


  1%|          | 1/166 [00:00<00:24,  6.81it/s]

4: Best candidate model is 97 with improvement of 0.00036
4: Best ensemble [53, 37, 117, 9, 97]
4: New ensemble score 0.93209


  1%|          | 1/166 [00:00<00:25,  6.49it/s]

5: Best candidate model is 107 with improvement of 0.00023
5: Best ensemble [53, 37, 117, 9, 97, 107]
5: New ensemble score 0.93232


  1%|          | 2/166 [00:00<00:15, 10.47it/s]

6: Best candidate model is 29 with improvement of 0.00037
6: Best ensemble [53, 37, 117, 9, 97, 107, 29]
6: New ensemble score 0.93269


  1%|          | 1/166 [00:00<00:24,  6.65it/s]

7: Best candidate model is 53 with improvement of 0.00007
7: Best ensemble [53, 37, 117, 9, 97, 107, 29, 53]
7: New ensemble score 0.93276


  1%|          | 1/166 [00:00<00:29,  5.66it/s]

8: Best candidate model is 56 with improvement of 0.00004
8: Best ensemble [53, 37, 117, 9, 97, 107, 29, 53, 56]
8: New ensemble score 0.93280


  1%|          | 1/166 [00:00<00:25,  6.50it/s]

9: Best candidate model is 130 with improvement of 0.00003
9: Best ensemble [53, 37, 117, 9, 97, 107, 29, 53, 56, 130]
9: New ensemble score 0.93283


  1%|          | 1/166 [00:00<00:25,  6.41it/s]

10: Best candidate model is 162 with improvement of 0.00020
10: Best ensemble [53, 37, 117, 9, 97, 107, 29, 53, 56, 130, 162]
10: New ensemble score 0.93303


  1%|          | 2/166 [00:00<00:14, 11.68it/s]

11: Best candidate model is 148 with improvement of 0.00007
11: Best ensemble [53, 37, 117, 9, 97, 107, 29, 53, 56, 130, 162, 148]
11: New ensemble score 0.93310


100%|██████████| 166/166 [00:15<00:00, 10.97it/s]


Can't optimize any more
Optimizing bag 2


  1%|          | 1/166 [00:00<00:23,  7.00it/s]

0: Best candidate model is 135 with improvement of 0.92763
0: Best ensemble [135]
0: New ensemble score 0.92763


  1%|          | 1/166 [00:00<00:24,  6.80it/s]

1: Best candidate model is 11 with improvement of 0.00284
1: Best ensemble [135, 11]
1: New ensemble score 0.93047


  1%|          | 1/166 [00:00<00:24,  6.85it/s]

2: Best candidate model is 128 with improvement of 0.00090
2: Best ensemble [135, 11, 128]
2: New ensemble score 0.93137


  1%|          | 1/166 [00:00<00:23,  7.05it/s]

3: Best candidate model is 22 with improvement of 0.00060
3: Best ensemble [135, 11, 128, 22]
3: New ensemble score 0.93197


  1%|          | 1/166 [00:00<00:24,  6.81it/s]

4: Best candidate model is 43 with improvement of 0.00028
4: Best ensemble [135, 11, 128, 22, 43]
4: New ensemble score 0.93225


  1%|          | 1/166 [00:00<00:25,  6.51it/s]

5: Best candidate model is 61 with improvement of 0.00040
5: Best ensemble [135, 11, 128, 22, 43, 61]
5: New ensemble score 0.93265


  1%|          | 2/166 [00:00<00:13, 12.48it/s]

6: Best candidate model is 151 with improvement of 0.00021
6: Best ensemble [135, 11, 128, 22, 43, 61, 151]
6: New ensemble score 0.93285


  1%|          | 2/166 [00:00<00:13, 12.16it/s]

7: Best candidate model is 115 with improvement of 0.00020
7: Best ensemble [135, 11, 128, 22, 43, 61, 151, 115]
7: New ensemble score 0.93306


  1%|          | 1/166 [00:00<00:25,  6.60it/s]

8: Best candidate model is 72 with improvement of 0.00008
8: Best ensemble [135, 11, 128, 22, 43, 61, 151, 115, 72]
8: New ensemble score 0.93313


100%|██████████| 166/166 [00:14<00:00, 11.35it/s]


Can't optimize any more
[0.9323389100225522, 0.93309579730886738, 0.93313127829213194]
Average score 0.93286

Iteration 4
Split to bas of 166 where last 166
Optimizing bag 0


  1%|          | 2/166 [00:00<00:11, 13.80it/s]

0: Best candidate model is 119 with improvement of 0.92669
0: Best ensemble [119]
0: New ensemble score 0.92669


  1%|          | 1/166 [00:00<00:23,  6.96it/s]

1: Best candidate model is 51 with improvement of 0.00310
1: Best ensemble [119, 51]
1: New ensemble score 0.92980


  1%|          | 2/166 [00:00<00:12, 13.40it/s]

2: Best candidate model is 126 with improvement of 0.00133
2: Best ensemble [119, 51, 126]
2: New ensemble score 0.93113


  1%|          | 1/166 [00:00<00:25,  6.47it/s]

3: Best candidate model is 133 with improvement of 0.00066
3: Best ensemble [119, 51, 126, 133]
3: New ensemble score 0.93179


  1%|          | 1/166 [00:00<00:24,  6.79it/s]

4: Best candidate model is 141 with improvement of 0.00041
4: Best ensemble [119, 51, 126, 133, 141]
4: New ensemble score 0.93220


  1%|          | 1/166 [00:00<00:25,  6.41it/s]

5: Best candidate model is 32 with improvement of 0.00033
5: Best ensemble [119, 51, 126, 133, 141, 32]
5: New ensemble score 0.93253


100%|██████████| 166/166 [00:13<00:00, 12.90it/s]


Can't optimize any more
Optimizing bag 1


  1%|          | 1/166 [00:00<00:23,  7.03it/s]

0: Best candidate model is 134 with improvement of 0.92730
0: Best ensemble [134]
0: New ensemble score 0.92730


  1%|          | 2/166 [00:00<00:11, 13.68it/s]

1: Best candidate model is 59 with improvement of 0.00286
1: Best ensemble [134, 59]
1: New ensemble score 0.93017


  1%|          | 1/166 [00:00<00:24,  6.73it/s]

2: Best candidate model is 40 with improvement of 0.00095
2: Best ensemble [134, 59, 40]
2: New ensemble score 0.93111


  1%|          | 1/166 [00:00<00:24,  6.82it/s]

3: Best candidate model is 43 with improvement of 0.00067
3: Best ensemble [134, 59, 40, 43]
3: New ensemble score 0.93179


  1%|          | 2/166 [00:00<00:12, 13.00it/s]

4: Best candidate model is 148 with improvement of 0.00055
4: Best ensemble [134, 59, 40, 43, 148]
4: New ensemble score 0.93234


  1%|          | 2/166 [00:00<00:12, 12.86it/s]

5: Best candidate model is 73 with improvement of 0.00020
5: Best ensemble [134, 59, 40, 43, 148, 73]
5: New ensemble score 0.93254


  1%|          | 1/166 [00:00<00:24,  6.63it/s]

6: Best candidate model is 97 with improvement of 0.00014
6: Best ensemble [134, 59, 40, 43, 148, 73, 97]
6: New ensemble score 0.93268


  1%|          | 1/166 [00:00<00:24,  6.62it/s]

7: Best candidate model is 144 with improvement of 0.00013
7: Best ensemble [134, 59, 40, 43, 148, 73, 97, 144]
7: New ensemble score 0.93280


  1%|          | 1/166 [00:00<00:25,  6.52it/s]

8: Best candidate model is 134 with improvement of 0.00002
8: Best ensemble [134, 59, 40, 43, 148, 73, 97, 144, 134]
8: New ensemble score 0.93283


  1%|          | 1/166 [00:00<00:27,  5.94it/s]

9: Best candidate model is 70 with improvement of 0.00003
9: Best ensemble [134, 59, 40, 43, 148, 73, 97, 144, 134, 70]
9: New ensemble score 0.93285


  1%|          | 2/166 [00:00<00:14, 11.66it/s]

10: Best candidate model is 90 with improvement of 0.00005
10: Best ensemble [134, 59, 40, 43, 148, 73, 97, 144, 134, 70, 90]
10: New ensemble score 0.93290


  1%|          | 2/166 [00:00<00:14, 11.58it/s]

11: Best candidate model is 159 with improvement of 0.00009
11: Best ensemble [134, 59, 40, 43, 148, 73, 97, 144, 134, 70, 90, 159]
11: New ensemble score 0.93299


  1%|          | 1/166 [00:00<00:17,  9.70it/s]

12: Best candidate model is 97 with improvement of 0.00002
12: Best ensemble [134, 59, 40, 43, 148, 73, 97, 144, 134, 70, 90, 159, 97]
12: New ensemble score 0.93301


100%|██████████| 166/166 [00:16<00:00, 10.22it/s]


Can't optimize any more
Optimizing bag 2


  1%|          | 2/166 [00:00<00:11, 13.89it/s]

0: Best candidate model is 82 with improvement of 0.92802
0: Best ensemble [82]
0: New ensemble score 0.92802


  1%|          | 1/166 [00:00<00:23,  6.95it/s]

1: Best candidate model is 114 with improvement of 0.00243
1: Best ensemble [82, 114]
1: New ensemble score 0.93045


  1%|          | 2/166 [00:00<00:12, 13.23it/s]

2: Best candidate model is 20 with improvement of 0.00107
2: Best ensemble [82, 114, 20]
2: New ensemble score 0.93152


  1%|          | 2/166 [00:00<00:12, 13.11it/s]

3: Best candidate model is 0 with improvement of 0.00082
3: Best ensemble [82, 114, 20, 0]
3: New ensemble score 0.93235


  1%|          | 1/166 [00:00<00:25,  6.59it/s]

4: Best candidate model is 78 with improvement of 0.00026
4: Best ensemble [82, 114, 20, 0, 78]
4: New ensemble score 0.93260


  1%|          | 2/166 [00:00<00:12, 12.79it/s]

5: Best candidate model is 162 with improvement of 0.00056
5: Best ensemble [82, 114, 20, 0, 78, 162]
5: New ensemble score 0.93316


  1%|          | 1/166 [00:00<00:25,  6.59it/s]

6: Best candidate model is 118 with improvement of 0.00022
6: Best ensemble [82, 114, 20, 0, 78, 162, 118]
6: New ensemble score 0.93339


100%|██████████| 166/166 [00:14<00:00, 11.25it/s]

Can't optimize any more
[0.93253013180903299, 0.93301207022898069, 0.93338583616532222]
Average score 0.93298


In [31]:
for ens_list in all_ensembles:
    print(ens_list)

vote_preds = []
for ens_list in all_ensembles:
    ensemble_preds = [preds_valid[j] for j in ens_list]
    p = (np.mean(ensemble_preds, axis=0) > 0.2).astype(int)
    vote_preds.append(p)
    
final_pred = vote(np.array(vote_preds))
vote_score = fbeta_score(y_true_valid, final_pred, beta=2, average='samples')
print("Vote score on validation set %.5f" % vote_score)

[435 408  87 337 138 484 443 421 118 179 372]
[483 110 355 455 141 403 336 140]
[482 177 381 112 433 373 482 235 137 112 382 339 420 433 373 112]
[455 446 372 112 393 177  52 339 395]
[435 482 337 408  22 359 435]
[484 381 141 138  23 355 122 484 344 342 137 461]
[443 138 359 119 408 122]
[482 383 337 112 419 484 141 339 355 401]
[435 110 343 423 387 336 373  22 118 177  43 432 455 423]
Vote score on validation set 0.93348
